SPACESHIP_RPROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true

SPACESHIP_DOCKER_SYMBOL="󰡨 "

SPACESHIP_BATTERY_SHOW=always
SPACESHIP_BATTERY_PREFIX="bat "

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR="#ff5f00"

SPACESHIP_ASYNC_SHOW=false

SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_LOCK_SYMBOL=" 󰌾"
SPACESHIP_DIR_TRUNC_PREFIX="…/"
SPACESHIP_DIR_COLOR="blue"

SPACESHIP_EXIT_CODE_SHOW=true

SPACESHIP_CHAR_PREFIX="󱞪 "
SPACESHIP_CHAR_SYMBOL="❯❯ "